CREATE TABLE IF NOT EXISTS users (
id           INT GENERATED     BY DEFAULT AS IDENTITY PRIMARY KEY,
email        VARCHAR(40)       NOT NULL,
login        VARCHAR(20)       NOT NULL,
name_user    VARCHAR(20),
birthday     DATE,
UNIQUE (email),
UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS genres (
id           INT               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name         VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS mpa (
id           INT               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name         VARCHAR(10)
);


CREATE TABLE IF NOT EXISTS films (
id           INT               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name         VARCHAR(100)      NOT NULL,
genre_id     INT               REFERENCES genres(id),
mpa_id       INT               REFERENCES mpa(id),
rate         INT,
description  VARCHAR(200),
release_date DATE,
duration     INT
);

CREATE TABLE IF NOT EXISTS film_genres (
film_id      INT               REFERENCES films(id),
genre_id     INT               REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS user_likes (
user_id      INT               REFERENCES users(id),
film_id      INT               REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS friends (
user_id      INT               REFERENCES users(id),
friend_id    INT               REFERENCES users(id)
);



